config/routes.rb
Rails.application.routes.draw do

  root 'balances#index'

  resources :balances

end

app/models/balance.rb
class Balance < ActiveRecord::Base
    def self.balance
       where("amount > ?", 0).sum("amount")
    end
    
    def self.debt
        where("amount < ?", 0).sum("amount")
    end
    
    def self.total
        sum("amount")
    end
  validates :title, :amount, :date, presence: true
end

app/models/record.rb
class Record < ActiveRecord::Base
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/balance_controller.rb
class BalanceController < ApplicationController
    def index
        @balances = Balance.all
    end
    def new
        @balance = Balance.new
    end
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
    def index
        @balances = Balance.all
        @balance = Balance.new
        @balance_debt = @balances.debt
        @balance_sum = @balances.balance
        @total = @balances.total
    end
    def create
        @create_balance = Balance.create(balance_params)
        if @create_balance.valid?
            flash[:success]= "Added successfully!"
            
        else
            flash[:error]= "Sorry, it couldnot be added. Try Again!"
        end
        redirect_to root_path
    end
    
    def edit
        @balance = Balance.find(params[:id])
        
    end
    def update
      @balance = Balance.find(params[:id])
      if @balance.update(balance_params)
          flash[:success]= "Edited successfully!"
        redirect_to root_path
      else
        flash[:error]= "Sorry, it couldnot be added. Try Again!"
        redirect_to edit_balance_path(params[:id])
      end
    end
    def destroy
        @balance = Balance.find(params[:id])
        @balance.destroy
        flash[:success]= "Deleted successfully!"
        redirect_to root_path
    end
    
    private
    def balance_params
        params.require(:balance).permit(:title, :amount, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/views/balances/edit.html.erb
<div class="container">
    <%= simple_form_for (@balance), method: :patch do |f| %>
              <%= f.input :title %>
              <%= f.input :amount %>
              <%= f.input :date, as: :date, start_year: Date.today.year -90,
                                          end_year: Date.today.year -12, discard_day: false,
                                  order: [:day, :month, :year] %>
              <%= f.submit 'Update', class:'btn btn-success' %>
    <% end %>
</div>

app/views/balances/index.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Add New Record</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for (@balance) do |f| %>
          <%= f.input :title %>
          <%= f.input :amount %>
          <%= f.input :date, as: :date, start_year: Date.today.year - 10,
                                      end_year: Date.today.year, discard_day: false,
                              order: [:day, :month, :year] %>
          
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Add', class:'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
    <h3>Balance: <%= @balance_sum %></h3>
    <h3>Debt: <%= @balance_debt %></h3>
    <h2>Total: <%= @total %></h2>
    <br /><br />
  <table class="table table-hover">
      <tr>
          <td><b>Date</b></td>
          <td><b>Title</b></td>
          <td><b>Amount</b></td>
          <td></td>
          <td></td>
      </tr>
      <% @balances.each do |balance| %>
      <tr>
          <td><%= balance.date %></td>
          <td><%= balance.title %></td>
          <td><%= balance.amount %></td>
          <td><%= link_to 'Edit', edit_balance_path(balance), class: 'btn btn-sm btn-warning', title:'Edit' %></td>
          <td><%= link_to 'Delete', balance_path(balance), method: :delete, class: 'btn btn-sm btn-danger', title:'Delete', data: {confirm: "Are you sure?"} %></td>
      </tr>
      <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>myDailyBalance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Lobster+Two|Slabo+27px" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/nav' %>
<%= render 'shared/flash_messages' %>
<%= yield %>

</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">myDailyBalance</a>
    </div>
      <ul class="nav navbar-nav navbar-right">
        <li><button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#myModal">
  New Record
</button></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>